Imports System.Data.SqlClient
Imports System.IO

Public Class frmMyBookings

    Private Sub frmMyBookings_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ' Load user booking history when the form opens
        LoadUserHistory()
    End Sub

    ' 1. Load history from database for the logged-in user
    Public Sub LoadUserHistory()
        Try
            ' Ensure loggedInUser contains the current session's username
            Dim currentUser As String = loggedInUser

            If conn.State = ConnectionState.Closed Then conn.Open()

            ' SQL Query to get booking details and the generated receipt text
            Dim sql As String = "SELECT BookingID, RoomID, CheckInDate, CheckOutDate, TotalAmount, PaymentStatus, ReceiptText " &
                               "FROM Bookings WHERE Username = @user ORDER BY BookingID DESC"

            Dim cmd As New SqlCommand(sql, conn)
            cmd.Parameters.AddWithValue("@user", currentUser)

            Dim adp As New SqlDataAdapter(cmd)
            Dim dt As New DataTable()
            adp.Fill(dt)

            DataGridView1.DataSource = dt
            CustomizeGrid() ' Apply visual styles
            conn.Close()
        Catch ex As Exception
            MsgBox("Error loading history: " & ex.Message, MsgBoxStyle.Critical)
            If conn.State = ConnectionState.Open Then conn.Close()
        End Try
    End Sub

    ' 2. UI Customization for the DataGridView
    Private Sub CustomizeGrid()
        With DataGridView1
            .AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill
            .AllowUserToAddRows = False
            .ReadOnly = True
            .SelectionMode = DataGridViewSelectionMode.FullRowSelect
            .BackgroundColor = Color.White
            .RowHeadersVisible = False
            .AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(245, 245, 245)
        End With

        ' Hide sensitive ID and long text columns from the main view
        If DataGridView1.Columns.Contains("BookingID") Then DataGridView1.Columns("BookingID").Visible = False
        If DataGridView1.Columns.Contains("ReceiptText") Then DataGridView1.Columns("ReceiptText").Visible = False

        ' Apply color coding based on PaymentStatus for better readability
        For Each row As DataGridViewRow In DataGridView1.Rows
            Dim status As String = row.Cells("PaymentStatus").Value.ToString()

            Select Case status
                Case "Rejected"
                    row.DefaultCellStyle.ForeColor = Color.Firebrick
                Case "Approved"
                    row.DefaultCellStyle.ForeColor = Color.DarkGreen
                Case "Completed"
                    row.DefaultCellStyle.ForeColor = Color.RoyalBlue
            End Select
        Next
    End Sub

    ' 3. Show receipt in a MsgBox when a row is clicked
    Private Sub DataGridView1_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles DataGridView1.CellClick
        If DataGridView1.SelectedRows.Count > 0 Then
            Dim status As String = DataGridView1.SelectedRows(0).Cells("PaymentStatus").Value.ToString()
            Dim receiptText = DataGridView1.SelectedRows(0).Cells("ReceiptText").Value

            If (status = "Approved" Or status = "Completed") AndAlso receiptText IsNot DBNull.Value Then
                ' Display the official receipt text generated by Admin
                MsgBox(receiptText.ToString(), MsgBoxStyle.Information, "Official Receipt Preview")
            ElseIf status = "Pending" Then
                MsgBox("Your payment is still under review. Please wait for Admin approval.", MsgBoxStyle.Information)
            ElseIf status = "Rejected" Then
                MsgBox("This booking was rejected. No receipt is available.", MsgBoxStyle.Critical)
            End If
        End If
    End Sub

    ' 4. Download Receipt as .txt and open with WPS Office
    Private Sub btnDownloadReceipt_Click(sender As Object, e As EventArgs) Handles btnDownloadReceipt.Click
        If DataGridView1.SelectedRows.Count > 0 Then
            Dim row As DataGridViewRow = DataGridView1.SelectedRows(0)
            Dim status As String = row.Cells("PaymentStatus").Value.ToString()
            Dim receiptContent = row.Cells("ReceiptText").Value

            ' Check if receipt exists
            If (status = "Approved" Or status = "Completed") AndAlso receiptContent IsNot DBNull.Value Then

                Dim sfd As New SaveFileDialog()
                sfd.Filter = "Text Files (*.txt)|*.txt"
                sfd.FileName = "Hotel_Receipt_Room_" & row.Cells("RoomID").Value.ToString() & ".txt"

                If sfd.ShowDialog() = DialogResult.OK Then
                    Try
                        ' Write content to the file
                        File.WriteAllText(sfd.FileName, receiptContent.ToString())
                        MsgBox("Receipt downloaded successfully!", MsgBoxStyle.Information)

                        ' Logic to open with WPS Office
                        Try
                            ' Common installation path for WPS Office
                            Dim wpsPath As String = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) & "\kingsoft\WPS Office\ksolaunch.exe"

                            If File.Exists(wpsPath) Then
                                ' Open specifically with WPS
                                Process.Start(wpsPath, sfd.FileName)
                            Else
                                ' Fallback to default text editor if WPS is not found
                                Process.Start(sfd.FileName)
                            End If
                        Catch
                            ' General fallback
                            Process.Start(sfd.FileName)
                        End Try

                    Catch ex As Exception
                        MsgBox("File System Error: " & ex.Message)
                    End Try
                End If
            Else
                MsgBox("No receipt available for the selected booking.", MsgBoxStyle.Exclamation)
            End If
        Else
            MsgBox("Please select a booking from the list first!")
        End If
    End Sub

    ' 5. Navigation & Refresh
    Private Sub btnBack_Click(sender As Object, e As EventArgs) Handles btnBack.Click
        frmCustomerDashboard.Show()
        Me.Close()
    End Sub

    Private Sub btnRefresh_Click(sender As Object, e As EventArgs) Handles btnRefresh.Click
        LoadUserHistory()
    End Sub

    Private Sub DataGridView1_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles DataGridView1.CellContentClick

    End Sub
End Class